version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    # Only minor/patch to avoid noisy breaking bumps
    allow:
      - dependency-type: "direct"
    ignore:
      # ignore majors across these to avoid churn
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastify"
        update-types: ["version-update:semver-major"]
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    # Let GitHub auto-merge only when CI is green
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    ignore:
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-major"]
    groups:
      gha-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]