# fly.staging.toml — p5 API (staging)

app = "p5-api-staging"
primary_region = "sin"

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  NODE_ENV = "staging"
  PORT = "80"                       # 👈 force app to listen on 80
  RATE_LIMIT_MAX = "100"
  RATE_LIMIT_TIME_WINDOW = "1 minute"
  # CORS_ORIGINS stays as a secret

[http_service]
  internal_port = 80                # 👈 must match the app’s listening port
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  # Ready check (DB reachability)
  [[http_service.checks]]
    interval = "10s"
    timeout  = "2s"
    grace_period = "20s"
    method = "get"
    path   = "/ready"

[checks]
  [checks.health]
    port = 80                       # 👈 health check hits 80 too
    type = "http"
    interval = "15s"
    timeout = "3s"
    grace_period = "20s"
    method = "get"
    path = "/health"

[vm]
  size = "shared-cpu-1x"
  memory = "512MB"

# IMPORTANT: no cmd = [...] here.
# Let the Dockerfile's CMD (node src/server.js) be the single source of truth.