# fly.toml — p5 API (production)
app = "p5-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

  dockerfile = "apps/api/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "80"
  RATE_LIMIT_MAX = "100"
  RATE_LIMIT_TIME_WINDOW = "1 minute"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    method = "get"
    path = "/ready"

[vm]
  size = "shared-cpu-1x"
  memory = "512MB"

cmd = ["node", "apps/api/src/server.js"]
