app = "p5-api-staging"
primary_region = "iad" # change to your closest if you want

[build]
  dockerfile = "apps/api/Dockerfile"

[env]
  NODE_ENV = "staging"
  PORT = "3000"
  RATE_LIMIT_MAX = "100"
  RATE_LIMIT_TIME_WINDOW = "1 minute"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    method = "get"
    path = "/ready"
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
