data_dir = "/var/lib/vector"

[sources.fly_app]
type = "http_server"
address = "0.0.0.0:8686"
decoding.codec = "json"

[sources.app_stdin]
type = "stdin"

[transforms.merge]
type = "remap"
inputs = ["fly_app","app_stdin"]
source = '''
. = .
'''

[sinks.s3_logs]
type = "aws_s3"
inputs = ["merge"]
bucket = "${S3_BUCKET}"
endpoint = "${S3_ENDPOINT}"
region = "${S3_REGION}"
compression = "gzip"
encoding.codec = "json"
key_prefix = "logs/date=%F/app="
filename_append_uuid = true
batch.timeout_secs = 10